name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print working directory
      run: pwd && ls -l


    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y autoconf automake libtool

    - name: Generate configure script 
      run: autoreconf -i
    
    - name: Run configure script
      run: ./configure
      
    - name: Run autogen.sh
      run: ./autogen.sh


    - name: Make configure executable
      run: chmod +x configure

  
